<?xml version="1.0"?>
<Compound xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <a>9.819</a>
  <b>9.819</b>
  <c>7.987</c>
  <name>LaSc3(BO3)4</name>
  <elList>
    <Element>
      <type>Lantanoid</type>
      <elenemtName>Lantan</elenemtName>
      <x>0.33333</x>
      <y>0.66667</y>
      <z>0.66667</z>
    </Element>
	<Element>
      <type>Scandium</type>
      <elenemtName>Scandium</elenemtName>
      <x>0.1179</x>
      <y>0.3333</y>
      <z>0.3333</z>
    </Element>
	<Element>
      <type>Bor1</type>
      <elenemtName>Bor1</elenemtName>
      <x>0</x>
      <y>0.5487</y>
      <z>0.5</z>
    </Element>
	<Element>
      <type>Bor2</type>
      <elenemtName>Bor1</elenemtName>
      <x>0</x>
      <y>0</y>
      <z>0.5</z>
    </Element>
	<Element>
      <type>Oxygen</type>
      <elenemtName>Oxygen1</elenemtName>
      <x>0.1406</x>
      <y>0.6863</y>
      <z>0.4818</z>
    </Element>
	<Element>
      <type>Oxygen</type>
      <elenemtName>Oxygen2</elenemtName>
      <x>0</x>
      <y>0.412</y>
      <z>0.5</z>
    </Element>
	<Element>
      <type>Oxygen</type>
      <elenemtName>Oxygen3</elenemtName>
      <x>0.140</x>
      <y>0.1398</y>
      <z>0.5</z>
    </Element>
  </elList>
</Compound>