<?xml version="1.0"?>
<Compound xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <a>9.796</a>
  <b>9.796</b>
  <c>7.96</c>
  <name>CeSc3(BO3)4</name>
  <elList>
    <Element>
      <type>Lantanoid</type>
      <elenemtName>Cesium</elenemtName>
      <xn>0</xn>
      <yn>0</yn>
      <zn>1</zn>
	  <xd>1</xd>
      <yd>1</yd>
      <zd>2</zd>
    </Element>
	<Element>
      <type>Scandium</type>
      <elenemtName>Scandium</elenemtName>
      <xn>0.452</xn>
      <yn>0</yn>
      <zn>1</zn>
	  <xd>1</xd>
      <yd>1</yd>
      <zd>2</zd>
    </Element>
	<Element>
      <type>Bor1</type>
      <elenemtName>Bor1</elenemtName>
	  <xn>0.5494</xn>
      <yn>0</yn>
      <zn>0</zn>
	  <xd>1</xd>
      <yd>1</yd>
      <zd>1</zd>
    </Element>
	<Element>
      <type>Bor2</type>
      <elenemtName>Bor2</elenemtName>
	  <xn>0</xn>
      <yn>0</yn>
      <zn>0</zn>
	  <xd>1</xd>
      <yd>1</yd>
      <zd>1</zd>
    </Element>
	<Element>
      <type>Oxygen</type>
      <elenemtName>Oxygen1</elenemtName>
      <xn>0.2115</xn>
      <yn>0.1914</yn>
      <zn>0.3187</zn>
	  <xd>1</xd>
      <yd>1</yd>
      <zd>1</zd>
    </Element>
	<Element>
      <type>Oxygen</type>
      <elenemtName>Oxygen2</elenemtName>
      <xn>0.1408</xn>
      <yn>0</yn>
      <zn>0</zn>
	  <xd>1</xd>
      <yd>1</yd>
      <zd>1</zd>
    </Element>
	<Element>
      <type>Oxygen</type>
      <elenemtName>Oxygen3</elenemtName>
	  <xn>0.4097</xn>
      <yn>0</yn>
      <zn>0</zn>
	  <xd>1</xd>
      <yd>1</yd>
      <zd>1</zd>	
    </Element>
  </elList>
</Compound>