<?xml version="1.0"?>
<Compound xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <a>9.819</a>
  <b>9.819</b>
  <c>7.987</c>
  <name>LaSc3(BO3)4</name>
  <elList>
    <Element>
      <type>Lantanoid</type>
      <elenemtName>Lantan</elenemtName>
      <xn>1</xn>
      <yn>2</yn>
      <zn>2</zn>
	  <xd>3</xd>
      <yd>3</yd>
      <zd>3</zd>
    </Element>
	<Element>
      <type>Scandium</type>
      <elenemtName>Scandium</elenemtName>
      <xn>0.1179</xn>
      <yn>1</yn>
      <zn>1</zn>
	  <xd>1</xd>
      <yd>3</yd>
      <zd>3</zd>
    </Element>
	<Element>
      <type>Bor1</type>
      <elenemtName>Bor1</elenemtName>
	  <xn>0</xn>
      <yn>0.5487</yn>
      <zn>1</zn>
	  <xd>1</xd>
      <yd>1</yd>
      <zd>2</zd>
    </Element>
	<Element>
      <type>Bor2</type>
      <elenemtName>Bor2</elenemtName>
	  <xn>0</xn>
      <yn>0</yn>
      <zn>1</zn>
	  <xd>1</xd>
      <yd>1</yd>
      <zd>2</zd>
    </Element>
	<Element>
      <type>Oxygen</type>
      <elenemtName>Oxygen1</elenemtName>
      <xn>0.1406</xn>
      <yn>0.6863</yn>
      <zn>0.4818</zn>
	  <xd>1</xd>
      <yd>1</yd>
      <zd>1</zd>
    </Element>
	<Element>
      <type>Oxygen</type>
      <elenemtName>Oxygen2</elenemtName>
      <xn>0</xn>
      <yn>0.412</yn>
      <zn>1</zn>
	  <xd>1</xd>
      <yd>1</yd>
      <zd>2</zd>
    </Element>
	<Element>
      <type>Oxygen</type>
      <elenemtName>Oxygen3</elenemtName>
	  <xn>0.140</xn>
      <yn>0.1398</yn>
      <zn>1</zn>
	  <xd>1</xd>
      <yd>1</yd>
      <zd>2</zd>	
    </Element>
  </elList>
</Compound>