<?xml version="1.0"?>
<Compound xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <a>9.763333</a>
  <b>9.763333</b>
  <c>7.919222</c>
  <name>NdSc3(BO3)4</name>
  <elList>
    <Element>
      <type>Lantanoid</type>
      <elenemtName>Neodymium</elenemtName>
      <xn>0</xn>
      <yn>0</yn>
      <zn>0</zn>
	  <xd>1</xd>
      <yd>1</yd>
      <zd>1</zd>
    </Element>
	<Element>
      <type>Scandium</type>
      <elenemtName>Scandium</elenemtName>
      <xn>0.545722</xn>
      <yn>0</yn>
      <zn>0</zn>
	  <xd>1</xd>
      <yd>1</yd>
      <zd>1</zd>
    </Element>
	<Element>
      <type>Bor1</type>
      <elenemtName>Bor1</elenemtName>
	  <xn>0</xn>
      <yn>0</yn>
      <zn>1</zn>
	  <xd>1</xd>
      <yd>1</yd>
      <zd>2</zd>
    </Element>
	<Element>
      <type>Bor2</type>
      <elenemtName>Bor2</elenemtName>
	  <xn>0</xn>
      <yn>0.446822</yn>
      <zn>1</zn>
	  <xd>1</xd>
      <yd>1</yd>
      <zd>2</zd>
    </Element>
	<Element>
      <type>Oxygen</type>
      <elenemtName>Oxygen1</elenemtName>
      <xn>0.852977</xn>
      <yn>0</yn>
      <zn>1</zn>
	  <xd>1</xd>
      <yd>1</yd>
      <zd>2</zd>
    </Element>
	<Element>
      <type>Oxygen</type>
      <elenemtName>Oxygen2</elenemtName>
      <xn>0.587313</xn>
      <yn>0</yn>
      <zn>1</zn>
	  <xd>1</xd>
      <yd>1</yd>
      <zd>2</zd>
    </Element>
	<Element>
      <type>Oxygen</type>
      <elenemtName>Oxygen3</elenemtName>
	  <xn>0.457966</xn>
      <yn>0.146266</yn>
      <zn>0.520477</zn>
	  <xd>1</xd>
      <yd>1</yd>
      <zd>1</zd>	
    </Element>
  </elList>
</Compound>