<?xml version="1.0"?>
<Compound xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <a>9.7960444</a>
  <b>9.7960444</b>
  <c>7.9600333</c>
  <name>PrSc3(BO3)4</name>
  <elList>
    <Element>
      <type>Lantanoid</type>
      <elenemtName>Praseodymium</elenemtName>
      <xn>0</xn>
      <yn>0</yn>
      <zn>0</zn>
	  <xd>1</xd>
      <yd>1</yd>
      <zd>1</zd>
    </Element>
	<Element>
      <type>Scandium</type>
      <elenemtName>Scandium</elenemtName>
      <xn>0.452922</xn>
      <yn>0</yn>
      <zn>0</zn>
	  <xd>1</xd>
      <yd>1</yd>
      <zd>1</zd>
    </Element>
	<Element>
      <type>Bor1</type>
      <elenemtName>Bor1</elenemtName>
	  <xn>0</xn>
      <yn>0</yn>
      <zn>1</zn>
	  <xd>1</xd>
      <yd>1</yd>
      <zd>2</zd>
    </Element>
	<Element>
      <type>Bor2</type>
      <elenemtName>Bor2</elenemtName>
	  <xn>0.549111</xn>
      <yn>0</yn>
      <zn>1</zn>
	  <xd>1</xd>
      <yd>1</yd>
      <zd>2</zd>
    </Element>
	<Element>
      <type>Oxygen</type>
      <elenemtName>Oxygen1</elenemtName>
      <xn>0.140466</xn>
      <yn>0</yn>
      <zn>1</zn>
	  <xd>1</xd>
      <yd>1</yd>
      <zd>2</zd>
    </Element>
	<Element>
      <type>Oxygen</type>
      <elenemtName>Oxygen2</elenemtName>
      <xn>0.544066</xn>
      <yn>0.858466</yn>
      <zn>0.484655</zn>
	  <xd>1</xd>
      <yd>1</yd>
      <zd>1</zd>
    </Element>
	<Element>
      <type>Oxygen</type>
      <elenemtName>Oxygen3</elenemtName>
	  <xn>0.14100</xn>
      <yn>0</yn>
      <zn>1</zn>
	  <xd>1</xd>
      <yd>1</yd>
      <zd>2</zd>	
    </Element>
  </elList>
</Compound>