<?xml version="1.0"?>
<Compound xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <a>9.745088</a>
  <b>9.745088</b>
  <c>7.904111</c>
  <name>SmSc3(BO3)4</name>
  <elList>
    <Element>
      <type>Lantanoid</type>
      <elenemtName>Samarium</elenemtName>
      <xn>0</xn>
      <yn>0</yn>
      <zn>0</zn>
	  <xd>1</xd>
      <yd>1</yd>
      <zd>1</zd>
    </Element>
	<Element>
      <type>Scandium</type>
      <elenemtName>Scandium</elenemtName>
      <xn>0.454433</xn>
      <yn>0</yn>
      <zn>0</zn>
	  <xd>1</xd>
      <yd>1</yd>
      <zd>1</zd>
    </Element>
	<Element>
      <type>Bor1</type>
      <elenemtName>Bor1</elenemtName>
	  <xn>0</xn>
      <yn>0</yn>
      <zn>1</zn>
	  <xd>1</xd>
      <yd>1</yd>
      <zd>2</zd>
    </Element>
	<Element>
      <type>Bor2</type>
      <elenemtName>Bor2</elenemtName>
	  <xn>0.54622</xn>
      <yn>0</yn>
      <zn>1</zn>
	  <xd>1</xd>
      <yd>1</yd>
      <zd>2</zd>
    </Element>
	<Element>
      <type>Oxygen</type>
      <elenemtName>Oxygen1</elenemtName>
      <xn>0.14111</xn>
      <yn>0</yn>
      <zn>1</zn>
	  <xd>1</xd>
      <yd>1</yd>
      <zd>2</zd>
    </Element>
	<Element>
      <type>Oxygen</type>
      <elenemtName>Oxygen2</elenemtName>
      <xn>0.541088</xn>
      <yn>0.858099</yn>
      <zn>0.486288</zn>
	  <xd>1</xd>
      <yd>1</yd>
      <zd>1</zd>
    </Element>
	<Element>
      <type>Oxygen</type>
      <elenemtName>Oxygen3</elenemtName>
	  <xn>0.409333</xn>
      <yn>0</yn>
      <zn>1</zn>
	  <xd>1</xd>
      <yd>1</yd>
      <zd>2</zd>	
    </Element>
  </elList>
</Compound>